Pages/DenyCookiePage.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace SNACKIS___Webb.Pages
{
    public class DenyCookiePageModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace SNACKIS___Webb.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Logging;
using SNACKIS___Webb.Models;
using SNACKIS___Webb.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Text.Json;
using System.Threading.Tasks;

namespace SNACKIS___Webb.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;
        private readonly Services.IGateway _gateway;
       
        public List<Category> Categories;
        [BindProperty(SupportsGet =true)]
        public List<Post> Posts { get; set; }

        public List<PostDiscussion> PostDiscussions { get; set; }

        [BindProperty(SupportsGet =true)]
        public string CatId { get; set; }

        public IndexModel(ILogger<IndexModel> logger, Services.IGateway gateway)
        {
            _logger = logger;
            _gateway = gateway;

        }

        public async Task OnGetAsync()
        {
            try
            {
                Categories = await _gateway.GetAllCategories();
                Posts = await _gateway.GetAllPosts();
            }
            catch (Exception)
            {

                RedirectToPage("Error");
            }
           
        }
    }
}

Pages/NewPostView.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Json;
using System.Text;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Configuration;
using SNACKIS___Webb.Models;
using SNACKIS___Webb.Services;

namespace SNACKIS___Webb.Pages
{
    public class NewPostViewModel : PageModel
    {
        private readonly IGateway _gateway;
        private readonly HttpClient _client;
        private readonly IConfiguration _configuration;

        [BindProperty(SupportsGet = true)]
        public string NewCatId { get; set; }

        [BindProperty(SupportsGet =true)]
        public Post NewPost { get; set; }

        [BindProperty(SupportsGet =true)]
        public Category CurrerntCategory { get; set; }

        public NewPostViewModel(IGateway gateway, HttpClient client, IConfiguration configuration)
        {
            _gateway = gateway;
            _client = client;
            _configuration = configuration;
        }

        public async Task<IActionResult> OnGetAsync()
        {
            try
            {
                CurrerntCategory = await _gateway.GetCategoryById(HttpContext, NewCatId);
                return Page();
            }
            catch (Exception)
            {
                return RedirectToPage("Error");
            }

        }
        public async Task<IActionResult> OnPostAsync() 
        {
           
            try
            {
                NewPost.CategoryId = NewCatId;   
                var newPostResponse = await _gateway.CreateNewPost(HttpContext, NewPost);
                return Page();
               
            }
            catch (Exception)
            {
                return RedirectToPage("Error");
            }

        }

    }
}

Pages/PostAndReplyView.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Json;
using System.Text;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Configuration;
using SNACKIS___Webb.Models;
using SNACKIS___Webb.Services;

namespace SNACKIS___Webb.Pages
{
    public class PostAndReplyViewModel : PageModel
    {
        private readonly IGateway _gateway;
        private readonly HttpClient _client;
        private readonly IConfiguration _configuration;
        private readonly IAuthGateway _authgateway;
        public PostAndReplyViewModel(IGateway gateway, HttpClient client, IConfiguration configuration, IAuthGateway authGateway)
        {
            _gateway = gateway;
            _client = client;
            _configuration = configuration;
            _authgateway = authGateway;
        }

        [BindProperty(SupportsGet = true)]
        public string PostId { get; set; }

        [BindProperty(SupportsGet = true)]
        public string DiscussionPostId { get; set; }

        [BindProperty(SupportsGet = true)]
        public PostDiscussion ClickedPostDiscussion { get; set; }

        [BindProperty(SupportsGet = true)]
        public Post ClickedPost { get; set; }

        [BindProperty]
        public PostDiscussion NewDiscussion { get; set; }

        [BindProperty]
        public List<Category> Categories{ get; set; }

        public UserLoginResponseModel User { get; set; }

        public async Task<IActionResult> OnGetAsync()
        {
            try
            {
                string Id = HttpContext.Session.GetString("Id");
                User = await _authgateway.GetLoggedInUserByModel(HttpContext, Id);
                Categories = await _gateway.GetAllCategories();

                if (!string.IsNullOrEmpty(PostId))
                {

                    ClickedPost = await _gateway.GetPostById(PostId, HttpContext);


                    return Page();
                }
                return Page();
            }
            catch (Exception)
            {
                return RedirectToPage("Error");
            }

        }
        public async Task<IActionResult> OnPost(string id)
        {

            try
            {
                id = PostId;
                var response = await _gateway.ReportPostById(HttpContext, id, ClickedPost);
                IActionResult resultPage = await OnGetAsync();
                return resultPage;
            }
            catch (Exception)
            {

                return RedirectToPage("Error");
            }     
        }
        public async Task<IActionResult> OnPostReportDiscussion(string id, string postId)
        {

            try
            {
                id = DiscussionPostId;
                postId = PostId;

                var reportDiscussionResponse = await _gateway.ReportPostDiscussion(HttpContext, id, ClickedPostDiscussion);
                IActionResult resultPage = await OnGetAsync();
                return resultPage;
            }
            catch (Exception)
            {

                return RedirectToPage("Error");
            }
        }
        public async Task<IActionResult> OnPostCreateDiscussion(string id) 
        {
            try
            {
                id = PostId;
                var response = await _gateway.CreateNewPostDiscussion(HttpContext, NewDiscussion);
                IActionResult resultPage = await OnGetAsync();
                return resultPage;
            }
            catch (Exception)
            {
                return RedirectToPage("Error");
            }
        }
        
    }
}

Pages/PostsInCategoryPage.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using SNACKIS___Webb.Models;

namespace SNACKIS___Webb.Pages
{
    public class PostsInCategoryPageModel : PageModel
    {
        
        private readonly Services.IGateway _gateway;

        public PostsInCategoryPageModel( Services.IGateway gateway)
        {           
            _gateway = gateway;
        }


        [BindProperty(SupportsGet =true)]
        public string CatId { get; set; }
        public List<Post> Posts { get; set; }
        public List<Category> Categories { get; set; }

        
        public async Task OnGetAsync()
        {
            try
            {
                if (!string.IsNullOrEmpty(CatId))
                {
                    Posts = await _gateway.GetPostsByCatId(CatId);
                }
                Categories = await _gateway.GetAllCategories();
            }
            catch (Exception)
            {
                RedirectToPage("Error");
            }
            
        }
        
    }
}

Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SNACKIS___Webb.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

Pages/User/UserPage.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Text;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Configuration;
using SNACKIS___Webb.Models;
using SNACKIS___Webb.Services;
using SNACKIS___Webb.Tools;

namespace SNACKIS___Webb.Pages.User
{
    public class UserPageModel : PageModel
    {
        private readonly IAuthGateway _authgateway;
        private readonly HttpClient _client;
        private readonly IConfiguration _configuration;
        
        public UserPageModel(IAuthGateway authgateway, HttpClient client, IConfiguration configuration)
        {
            _authgateway = authgateway;
            _client = client;
            _configuration = configuration;
           
        }

        public UserLoginResponseModel User { get; set; }

        public async Task<IActionResult> OnGetAsync()
        {
            try
            {
                string Id = HttpContext.Session.GetString("Id");
                User = await _authgateway.GetLoggedInUserByModel(HttpContext, Id);
                return Page();
            }
            catch (Exception)
            {

                return NotFound();
            }   
     
        }
    }
}

Pages/UserPage.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace SNACKIS___Webb.Pages
{
    public class UserPageModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

Pages/DenyCookiePage.cshtml
@page
@model SNACKIS___Webb.Pages.DenyCookiePageModel
@{
}

<h2>Viktig information</h2>
<p>För att använda vår webapplikation måste du godkänna användandet av cookies. Du kommer fortfarande kunna använda sidan även om du inte klicka godkänn men genom att göra det godkänner du villkoren.</p>

<a href="/Index">Tillbaka till startsidan</a>

Pages/Index.cshtml
@page
@model IndexModel
@using SNACKIS___Webb.Tools;
@{
    ViewData["Title"] = "Home page";

}




<head>
    <link rel="stylesheet" href="~/css/IndexStyle.css">
    

</head>

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.0-2/css/all.min.css" integrity="sha256-46r060N2LrChLLb5zowXQ72/iKKNiw/lAmygmHExk/o=" crossorigin="anonymous" />
<div class="container">
    
    <div class="main-body p-0">
        <nav class="nav nav-pills nav-justified mobile-view justify-content-center">
            @if (Model.Categories != null)
            {
                @foreach (var cat in Model.Categories)
                {

                    <a class="btn btn-info" style="margin:2px;" asp-page="/PostsInCategoryPage" asp-route-CatId="@cat.Id">@cat.Title</a><br />

                }

            }

        </nav>
        <div class="inner-wrapper">           
            <div class="inner-sidebar text-center desktop-view">
                <h3>Kategorier</h3>                
                <div class="inner-sidebar-body p-0">
                    <div class="p-3 h-100" data-simplebar="init">
                        <div class="simplebar-wrapper" style="margin: -16px;">
                            <div class="simplebar-height-auto-observer-wrapper"><div class="simplebar-height-auto-observer"></div></div>
                            <div class="simplebar-mask">
                                <div class="simplebar-offset" style="right: 0px; bottom: 0px;">
                                    <div class="simplebar-content-wrapper" style="height: 100%;">
                                        <div class="simplebar-content" style="padding: 16px;">
                                            <nav class="nav nav-pills nav-gap-y-1 flex-column">


                                                @foreach (var cat in Model.Categories)
                                                {

                                                    <a class="btn btn-info" asp-page="/PostsInCategoryPage" asp-route-CatId="@cat.Id">@cat.Title</a><br />

                                                }

                                            </nav>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="simplebar-placeholder" style="width: 234px; height: 292px;"></div>
                        </div>
                        <div class="simplebar-track simplebar-horizontal" style="visibility: hidden;"><div class="simplebar-scrollbar" style="width: 0px; display: none;"></div></div>
                        <div class="simplebar-track simplebar-vertical" style="visibility: visible;"><div class="simplebar-scrollbar" style="height: 151px; display: block; transform: translate3d(0px, 0px, 0px);"></div></div>
                    </div>
                </div>

            </div>

            <div class="inner-main">

                <div class="inner-main-body p-2 p-sm-3 collapse forum-content show">
                    @foreach (var item in Model.Posts)
                    {

                        <div class="card mb-2">
                            <div class="card-body p-2 p-sm-3">
                                <p>@item.User.userName</p>

                                <div class="media forum-item">
                                    @if (item.User.Image == null)
                                    {

                                        <img src="https://bootdey.com/img/Content/avatar/avatar1.png" class="mr-3 rounded-circle" width="50" alt="User" />
                                    }
                                    else
                                    {
                                        <img src="/img/@item.User.Image" class="mr-3 rounded-circle" width="50" alt="User" />
                                    }

                                    <div class="media-body">
                                        <h5 class="card-title">
                                            <a asp-page="/PostAndReplyView" asp-route-PostId="@item.Id" class="forum-item-title">@item.Title</a><br />
                                        </h5>
                                        <p class="text-secondary">
                                            @item.Content
                                        </p>
                                    </div>
                                    <div class=" text-muted">
                                        <small>@item.Date</small>
                                    </div>
                                    
                                </div>
                            </div>
                        </div>
                    }
                </div>
            </div>
            
        </div>

        <div class="modal fade" id="threadModal" tabindex="-1" role="dialog" aria-labelledby="threadModalLabel" aria-hidden="true">
            <div class="modal-dialog modal-lg" role="document">
                <div class="modal-content">
                    <form>
                        <div class="modal-header d-flex align-items-center bg-primary text-white">
                            <h6 class="modal-title mb-0" id="threadModalLabel">New Discussion</h6>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">×</span>
                            </button>
                        </div>
                        <div class="modal-body">
                            <div class="form-group">
                                <label for="threadTitle">Title</label>
                                <input type="text" class="form-control" id="threadTitle" placeholder="Enter title" autofocus="" />
                            </div>
                            <textarea class="form-control summernote" style="display: none;"></textarea>

                            <div class="custom-file form-control-sm mt-3" style="max-width: 300px;">
                                <input type="file" class="custom-file-input" id="customFile" multiple="" />
                                <label class="custom-file-label" for="customFile">Attachment</label>
                            </div>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-light" data-dismiss="modal">Cancel</button>
                            <button type="button" class="btn btn-primary">Post</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

Pages/NewPostView.cshtml
@page
@model SNACKIS___Webb.Pages.NewPostViewModel
@{
}

<head>
    <link href="~/css/NewPostStyling.css" rel="stylesheet" />
</head>

<h1>Skapa tråd i kategorin @Model.CurrerntCategory.Title</h1>
<form asp-page-handler="Post">
<div asp-validation-summary="ModelOnly" class="text-danger"></div>
<div class="form-group" style="visibility: hidden">
    <input asp-for="NewCatId" class="form-control" value="@Model.NewCatId" />
    <span asp-validation-for="NewPost.CategoryId" class="text-danger"></span>
</div>

<div class="form-group">
    <label class="control-label">Titel</label>
    <input asp-for="NewPost.Title" class="form-control" autocomplete="off" />
    <span asp-validation-for="NewPost.Title" class="text-danger"></span>
</div>
<button class="btn btn-info" type="submit">Skapa tråd</button>
</form>

Pages/PostAndReplyView.cshtml
@page
@model SNACKIS___Webb.Pages.PostAndReplyViewModel
@{
    @using Microsoft.AspNetCore.Http
    @inject IHttpContextAccessor HttpContextAccessor
    bool returnTokenValue = HttpContextAccessor.HttpContext.Session.GetString("Role") is not null;
}

<head>
    <link rel="stylesheet" href="~/css/IndexStyle.css">
</head>
<div class="container">
    <div class="main-body p-0">
        <nav class="nav nav-pills nav-justified mobile-view justify-content-center">
            @foreach (var cat in Model.Categories)
            {

                <a class="btn btn-info" style="margin:2px;" asp-page="/PostsInCategoryPage" asp-route-CatId="@cat.Id">@cat.Title</a><br />

            }
        </nav>
        <div class="inner-wrapper">
            <div class="inner-sidebar text-center desktop-view">
                <h3>Kategorier</h3>
                <div class="inner-sidebar-body p-0">
                    <div class="p-3 h-100" data-simplebar="init">
                        <div class="simplebar-wrapper" style="margin: -16px;">
                            <div class="simplebar-height-auto-observer-wrapper"><div class="simplebar-height-auto-observer"></div></div>
                            <div class="simplebar-mask">
                                <div class="simplebar-offset" style="right: 0px; bottom: 0px;">
                                    <div class="simplebar-content-wrapper" style="height: 100%; ">
                                        <div class="simplebar-content" style="padding: 16px;">
                                            <nav class="nav nav-pills nav-gap-y-1 flex-column">
                                                @foreach (var cat in Model.Categories)
                                                {

                                                    <a class="btn btn-info" asp-page="/PostsInCategoryPage" asp-route-CatId="@cat.Id">@cat.Title</a><br />

                                                }
                                            </nav>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="simplebar-placeholder" style="width: 234px; height: 292px;"></div>
                        </div>
                        <div class="simplebar-track simplebar-horizontal" style="visibility: hidden;"><div class="simplebar-scrollbar" style="width: 0px; display: none;"></div></div>
                        <div class="simplebar-track simplebar-vertical" style="visibility: visible;"><div class="simplebar-scrollbar" style="height: 151px; display: block; transform: translate3d(0px, 0px, 0px);"></div></div>
                    </div>
                </div>
            </div>
            <div class="inner-main">
                <div class="inner-main-body p-2 p-sm-3 collapse forum-content show">
                    <h3>Tråd: @Model.ClickedPost.Title</h3>
                    <div class="card mb-2" style="outline : 3px solid lightblue">
                        <div class="card-body p-2 p-sm-3">

                            <p>@Model.ClickedPost.User.userName</p>

                            <div class="media forum-item">
                                @if (Model.ClickedPost.User.Image == null)
                                {
                                <a href="#" data-toggle="collapse" data-target=".forum-content"><img src="https://bootdey.com/img/Content/avatar/avatar1.png" class="mr-3 rounded-circle" width="50" alt="User" /></a>
                                }
                                else
                                {
                                <a href="#" data-toggle="collapse" data-target=".forum-content"><img src="/img/@Model.ClickedPost.User.Image" class="mr-3 rounded-circle" width="50" alt="User" /></a>
                                }

                                <div class="media-body">

                                    <p class="text-secondary">
                                        <strong>@Model.ClickedPost.Title</strong><br />
                                        @Model.ClickedPost.Content

                                    </p>
                                    <small>@Model.ClickedPost.Date</small>
                                </div>
                                @if (returnTokenValue)
                                {
                                <div class="text-muted small text-center align-self-center">
                                    <form class="report-btn" asp-page-handler="Post">
                                        <div  style="visibility : hidden">
                                            <input  asp-for="PostId" value="@Model.ClickedPost.Id" />
                                        </div>
                                        <input class="btn btn-danger btn-sm" type="submit" value="Anmäl" />
                                    </form>
                                </div>
                                }
                            </div>
                        </div>

                    </div>
                    @if (Model.ClickedPost.PostDiscussions != null)
                    {
                    @foreach (var item in Model.ClickedPost.PostDiscussions.OrderBy(x => x.Date))
                        {
                    <div class="card mb-2">
                        <div class="card-body p-2 p-sm-3">
                            <p>@item.User.userName</p>
                            <div class="media forum-item">
                                @if (item.User.Image == null)
                                        {
                                <a href="#" data-toggle="collapse" data-target=".forum-content"><img src="https://bootdey.com/img/Content/avatar/avatar1.png" class="mr-3 rounded-circle" width="50" alt="User" /></a>
                                        }
                                        else
                                        {
                                <a href="#" data-toggle="collapse" data-target=".forum-content"><img src="/img/@item.User.Image" class="mr-3 rounded-circle" width="50" alt="User" /></a>
                                        }
                                <div class="media-body">

                                    <p class="text-secondary">
                                        @item.Discussion
                                    </p>
                                    <div class=" text-muted">
                                        <small>@item.Date</small>
                                    </div>
                                </div>
                                @if (returnTokenValue)
                                        {
                                <div class="text-center align-self-center ">
                                    <form class="report-btn" asp-page-handler="ReportDiscussion">
                                        <div style="visibility : hidden">
                                            <input asp-for="PostId" value="@Model.PostId" />
                                            <input asp-for="DiscussionPostId" class="btn btn-danger" value="@item.Id" />
                                        </div>
                                        <input class="btn btn-danger btn-sm" type="submit" value="Anmäl" />
                                    </form>
                                </div>
                                         }
                            </div>
                        </div>
                    </div>


                        }

                    }
                            @if(Model.ClickedPost.PostDiscussions == null && returnTokenValue )
                            {
                                <div class="row">
                                    <div class="col-sm-10">
                                        <div class="alert-success" role="alert">
                                            <h3>Bli den första med att svara på den här tråden!</h3>
                                        </div>
                                    </div>
                                </div>

                            }

                    @if (returnTokenValue)
                    {

                    <form asp-page-handler="CreateDiscussion">
                        <div class="form-group" style="visibility: hidden">
                            <input asp-for="PostId" class="form-control" value="@Model.PostId" />
                        </div>
                        <div class="form-group">
                            <label for="">Skriv ditt svar här</label>
                            <textarea class="form-control" name="discussion" id="exampleFormControlTextarea1" rows="3"></textarea>
                        </div>
                        <div class="row">
                            <div class="col-sm-10">
                                <input class="btn btn-success" type="submit" value="Svara" />
                                <a class="btn btn-info" style="max-height : 100px ; max-width :200px ; align-content : center" href="/Index">Startsida</a>
                            </div>
                        </div>

                    </form>

                    }
                    else
                    {
                    <div class="row">
                        <div class="col-sm-10">
                            <strong class="text-danger">Du måste vara inloggad för att göra inlägg</strong><br />
                            <a asp-page="Auth/RegisterPage" class="btn btn-success" style="max-height : 100px ; max-width :200px ; align-content : center">Skapa konto</a>

                            <a asp-page="Auth/LoginPage" class="btn btn-info" style="max-height : 100px ; max-width :200px ; align-content : center">Logga in</a>
                            <a class="btn btn-info" style="max-height : 100px ; max-width :200px ; align-content : center" href="/Index">Startsida</a>
                        </div>
                    </div>
                    }




                </div>
            </div>
        </div>
    </div>
</div>